{{- if or .Values.secrets.data.llmApiKey .Values.secrets.data.webSearchApiKey .Values.secrets.data.moiApiKey .Values.secrets.data.viteSiliconflowApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "china-mobile-demo.fullname" . }}-secret
  labels:
    {{- include "china-mobile-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.secrets.data.llmApiKey }}
  llmApiKey: {{ .Values.secrets.data.llmApiKey | quote }}
{{- end }}
{{- if .Values.secrets.data.webSearchApiKey }}
  webSearchApiKey: {{ .Values.secrets.data.webSearchApiKey | quote }}
{{- end }}
{{- if .Values.secrets.data.moiApiKey }}
  moiApiKey: {{ .Values.secrets.data.moiApiKey | quote }}
{{- end }}
{{- if .Values.secrets.data.viteSiliconflowApiKey }}
  viteSiliconflowApiKey: {{ .Values.secrets.data.viteSiliconflowApiKey | quote }}
{{- end }}
{{- end }}

